import sys
import os
import importlib
from pathlib import Path
from contextlib import contextmanager

sys.path.insert(0, '/home/mmaliar/prosperity4-tester-private/venv/lib/python3.14/site-packages')
sys.path.insert(0, '/home/mmaliar/prosperity4-tester-private/trader-logic/round-2')

import prosperity4bt.datamodel as model
sys.modules['datamodel'] = model

from prosperity4bt.file_reader import FileSystemReader
from prosperity4bt.models import TradeMatchingMode
from prosperity4bt.data import read_day_data
from prosperity4bt.runner import prepare_state, type_check_orders, enforce_limits, match_orders, create_activity_logs
from prosperity4bt.datamodel import TradingState, Observation
from prosperity4bt.models import BacktestResult, SandboxLogRow

try18 = __import__("try18-debug")
trader = try18.Trader()

class MockReader:
    @contextmanager
    def file(self, parts):
        fake_path = "/home/mmaliar/prosperity4-tester-private/fake-round2-data-with-more-volume"
        name = parts[-1] 
        p = Path(fake_path) / name
        if p.exists():
            yield p
        else:
            yield None

reader = MockReader()
data = read_day_data(reader, 2, 6, True)
timestamps = sorted(data.prices.keys())
timestamp = timestamps[0]

state = TradingState(
    traderData="", timestamp=timestamp, listings={}, order_depths={},
    own_trades={}, market_trades={}, position={}, observations=Observation({}, {})
)

result = BacktestResult(round_num=2, day_num=6, sandbox_logs=[], activity_logs=[], trades=[])

prepare_state(state, data)
orders, conversions, trader_data = trader.run(state)

print("Orders generated by trader:")
for product, prod_orders in orders.items():
    print(f"Product: {product}")
    for o in prod_orders:
        print(f"  {o.quantity} units @ {o.price}")

sandbox_row = SandboxLogRow(timestamp=timestamp, sandbox_log="", lambda_log="")

type_check_orders(orders)
enforce_limits(state, data, orders, sandbox_row)

print(f"\nSandbox log after limits: {sandbox_row.sandbox_log}")

print("\nOrders after limits:")
for product, prod_orders in orders.items():
    print(f"Product: {product}")
    for o in prod_orders:
        print(f"  {o.quantity} units @ {o.price}")

match_orders(state, data, orders, result, TradeMatchingMode.worse)

print("\nMatched Trades:")
for t in result.trades:
    print(t)
    
print("\nNext tick position would be:")
print(state.position)
